### ISSUE TITLE
Identifying Animacy

### ISSUE THREAD

**Issue by Wafaa014** [rewicks/ctxpro#1]
Hello, 
thank you for the useful pipeline. Can you please include instructions to identify animacy? The current documentation of the identify function only includes out-of-English rules.

**Comment by rewicks** [comment]
Hi! Thanks for your interest and sorry for the delay.

We leverage the fact that the animacy ambiguity with into-English is directly parallel with the gender ambiguity _out-of_ English. To extract these instances, you can run the DE_GENDER (for instance) and then reverse the direction of the output `.json` files with the `scripts/reverse.py` file. 

I'll add a note to the README.
